version: '3.4'

services:
  db:
    image: records:v1
    volumes:
      - ./pg-data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    environment:
      - "POSTGRES_USER=pguser"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=record_collection"
      - "PGDATA=/var/lib/postgresql/data/pgdata"

volumes:
  pg-data: